### ISSUE TITLE
Feedback form in contribution guideline can't be accessed as it's private

### ISSUE THREAD

**Issue by JaapRood** [opticdev/docs#1]
Going through the docs about how to contribute (https://github.com/opticdev/docs/blob/master/open-source/how-to-contribute.md), I noticed how the embedded TypeForm can't be used as it's set to private:

![Screenshot 2020-03-18 at 11 53 43](https://user-images.githubusercontent.com/857549/76954029-f2f83480-690f-11ea-9207-9da6571de750.png)

**Comment by acunniffe** [comment]
Thanks @JaapRood. Just fixed this  -- we have some new docs coming soon that will be managed on the public github so everyone can contribute to them :)
